version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: zero44/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: zero44/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static:/frontend_static
    command: sh -c "npm run build && cp -r /app/build/. /frontend_static/"

  gateway:
    image: zero44/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
